### PR TITLE
33 medusa archer2

### PR DESCRIPTION
**Pull request by jupalm**
Made some adaptation to run the river nutrients, and finally pushed and test everything to make sure that anyone could just pulled the code and run without changing anything.
this part is OK for MEDUSA - orca025 on Archer2.

But since i've made my branch, quite few commits have been made on the main. mainly about Anemone or ORCA1.  
My changes should still be OK, but it seems i need to rebase with a new pull request. 
let see how that works

### CODE REVIEW

**Comment by jupalm** [comment]
It's very confusing... 
i should have to rebase, it was mentioned before i made the pulled request... 
and now there is no mention of it anymore...      
i'll try-again from a fresh download, just to be sure.
the page mentions 2 conflicts, i'll see what it is about

**Comment by jupalm** [comment]
rebase done, now testing ^^

**Comment by jupalm** [comment]
1 problem that seems to be also in the dynamic eORCA025 namelist, the init file for T and S has not been updated.

**Comment by atb299** [comment]
@jupalm , I'll take a look in a little while. At first glance the namelist_cfg is just a link to the one in GLOBAL_QCO, so updating that to the latest should be OK.

**Comment by atb299** [comment]
Sounds good, @jupalm ! I have a complete set of the files on Archer, here: /work/n01/n01/atb299/NPD_eORCA025_v4.2. I think we just need to get Andrew to copy the missing files into the shared folder.

**Comment by atb299** [comment]
@jupalm, I've just tested it too, pointing to /work/n01/n01/atb299/NPD_eORCA025_v4.2. I needed to change namelist_cfg to pick up woa*_gaussian_smoothed.nc and the link shlat2d.nc -> INPUT/shlat2d_eORCA025_southps_v4.2.nc. We can fix these later when the files are in the shared folder. Until then, I'm happy to merge...

**Pull request merged**
